import { Demo } from "@/types/demo";

const demoData: Demo[] = [
  {
    id: 1,
    slug: "rock-alternativo",
    title: "Rock Alternativo",
    description: "Banda de rock alternativo con un sonido potente y letras profundas.",
    thumbnail: "/images/blog/blog-01.jpg",
    videoUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    category: "Rock",
    artist: {
      name: "Los Insurgentes",
      image: "/images/blog/author-01.png",
      bio: "Banda de rock alternativo formada en 2020. Su música combina riffs potentes con letras que abordan temas sociales y personales.",
    },
    stats: {
      views: 1500,
      likes: 580,
      shares: 95,
    },
    tags: ["rock", "alternativo", "banda"],
    publishDate: "2025-02-20",
  },
  {
    id: 2,
    slug: "jazz-vocal",
    title: "Jazz Vocal",
    description: "Vocalista de jazz con un estilo único y contemporáneo.",
    thumbnail: "/images/blog/blog-02.jpg",
    videoUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    category: "Jazz",
    artist: {
      name: "Laura González",
      image: "/images/blog/author-02.png",
      bio: "Vocalista de jazz con más de 10 años de experiencia en la escena musical. Su estilo único combina elementos tradicionales del jazz con influencias contemporáneas.",
    },
    stats: {
      views: 1200,
      likes: 450,
      shares: 89,
    },
    tags: ["jazz", "vocal", "contemporáneo"],
    publishDate: "2025-02-18",
  },
  {
    id: 3,
    slug: "electronica",
    title: "Demo Electrónico",
    description: "Productor de EDM con un sonido fresco e innovador.",
    thumbnail: "/images/blog/blog-03.jpg",
    videoUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    category: "Electrónica",
    artist: {
      name: "DJ Pulse",
      image: "/images/blog/author-03.png",
      bio: "Productor de música electrónica con un enfoque en sonidos experimentales y ritmos bailables.",
    },
    stats: {
      views: 980,
      likes: 320,
      shares: 45,
    },
    tags: ["edm", "electrónica", "dance"],
    publishDate: "2025-02-15",
  },
  {
    id: 4,
    slug: "jazz-fusion",
    title: "Jazz Fusion",
    description: "Proyecto de jazz fusion con influencias latinas.",
    thumbnail: "/images/blog/blog-01.jpg",
    videoUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    category: "Jazz",
    artist: {
      name: "Carlos Mendoza",
      image: "/images/blog/author-01.png",
      bio: "Músico versátil con experiencia en jazz y música latina. Su proyecto fusiona elementos tradicionales del jazz con ritmos latinos contemporáneos.",
    },
    stats: {
      views: 980,
      likes: 320,
      shares: 45,
    },
    tags: ["jazz", "fusion", "latino"],
    publishDate: "2025-02-14",
  },
  {
    id: 5,
    slug: "pop-indie",
    title: "Pop Indie",
    description: "Artista indie con un sonido pop fresco y original.",
    thumbnail: "/images/blog/blog-02.jpg",
    videoUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    category: "Pop",
    artist: {
      name: "Marina Torres",
      image: "/images/blog/author-02.png",
      bio: "Cantautora indie con un estilo único que mezcla pop alternativo con elementos electrónicos y letras personales.",
    },
    stats: {
      views: 850,
      likes: 290,
      shares: 38,
    },
    tags: ["pop", "indie", "alternativo"],
    publishDate: "2025-02-12",
  },
  {
    id: 6,
    slug: "hip-hop-experimental",
    title: "Hip Hop Experimental",
    description: "Proyecto de hip hop que rompe los límites del género.",
    thumbnail: "/images/blog/blog-03.jpg",
    videoUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    category: "Hip Hop",
    artist: {
      name: "Alex Ramírez",
      image: "/images/blog/author-03.png",
      bio: "Productor y MC que explora nuevas fronteras en el hip hop, incorporando elementos de música experimental y electrónica.",
    },
    stats: {
      views: 720,
      likes: 245,
      shares: 32,
    },
    tags: ["hip hop", "experimental", "electrónica"],
    publishDate: "2025-02-10",
  },
];

export default demoData;
